### ISSUE TITLE
IonMenu contentId attribute not recognized

### ISSUE THREAD

**Issue by a-Leong** [ModusCreateOrg/ionic-vue#136] opened 2020-08-05 18:57 UTC
_In Vue 3 prerelease_

I'm encountering a consistent issue where the IonMenu's required `contentId` attribute is not recognized. The menu does not work, an error is thrown and these messages appear in the console:
```console
[DEPRECATED][ion-menu] Using the [main] attribute is deprecated, please use the "contentId" property instead:
BEFORE:
  <ion-menu>...</ion-menu>
  <div main>...</div>

AFTER:
  <ion-menu contentId="main-content"></ion-menu>
  <div id="main-content">...</div>


Menu: must have a "content" element to listen for drag events on.
```

Inspecting the IonMenu element, the attribute is `contentid`(incorrectly cased). Occasionally, hot-reloading after a modification to the file containing the IonMenu temporarily fixes the issue and in those cases the attribute is correctly `content-id`.

Replicated in sample app:
```json
"@ionic/core": "^5.3.1",
"@modus/ionic-vue": "^3.0.0-alpha.13",
"vue": "^3.0.0-rc.5",
```

```vue
<template>
  <ion-app>
    <!--
    kebab-case produces same behavior
    <ion-menu content-id="main-content"></ion-menu>
    -->
    <ion-menu contentId="main-content"></ion-menu>
    <ion-content id="main-content">
      <ion-menu-button />
    </ion-content>
  </ion-app>
</template>

<script>
import { IonApp, IonMenu, IonContent, IonMenuButton } from '@modus/ionic-vue'

export default {
  name: 'App',
  components: {
    IonApp,
    IonMenu,
    IonContent,
    IonMenuButton,
  },
}
</script>

```

```javascript
import { createApp } from 'vue'
import { IonicVue, createRouter } from '@modus/ionic-vue'
import { createWebHistory } from 'vue-router'
import App from './App.vue'
import '@ionic/core/css/ionic.bundle.css'

const router = createRouter({
  history: createWebHistory(),
  routes: [
    {
      path: '/',
      component: App,
    },
  ],
})

const app = createApp(App)
app.use(IonicVue)
app.use(router)
app.mount('#app')

```

**Comment by michaeltintiuc** [comment] 2020-08-06 08:15
Thanks for creating the issue, this should be fixed soon with a newer version of ionic/core, the issue as you've noticed is the casing, unfortunately with Vue3 it's impossible (at least for the time being) to force prop and event casing, I've worked with the ionic team on this and the result is the ability to define custom casing when registering custom elements. I plan on getting this resolved within a few days as tops.

**Comment by michaeltintiuc** [comment] 2020-08-06 11:02
I've just looked at it again and it doesn't have to do with anything I've described above, will try to reproduce it locally, have you tried using IonMenu instead of ion-menu?

**Comment by a-Leong** [comment] 2020-08-06 16:12
Yes, same issue using IonMenu

**Comment by michaeltintiuc** [comment] 2020-08-06 20:09
I've just tried with the same versions as you, everything seems to be working just fine, here's the ionic/vue3 examples app I'm testing everything with: https://github.com/michaeltintiuc/ionic-vue-3-example

**Comment by michaeltintiuc** [comment] 2020-08-06 20:10
Try removing node_modules and reinstalling, for some reason it seems like updating to newer versions without doing that breaks stuff

**Comment by a-Leong** [comment] 2020-08-06 22:20
I had tried removing and reinstalling node_modules, but after your suggestion I removed package-lock.json as well and that did the trick. Thanks so much for your help!

**Comment by michaeltintiuc** [comment] 2020-08-06 22:21
Happy to help!

**Closed** 2020-08-06 22:31 UTC
Labels: bug, v3
